export type YogaPosition = { graha_id: number; rasi_id: number; bhava: number };
export type YogaRule = { rule_code:string; name:string; formation_conditions:Record<string,unknown>; planets_involved:string[]; houses_involved:number[] };
export type YogaEvaluation = { rule_code:string; formation_status:"FORMED"|"NOT_FORMED"; qualification:string; strength:"PRIMARY"|"NONE"; matched_conditions:string[]; failed_conditions:string[]; evidence:Record<string,unknown>; engine_version:"YOGA_ENGINE_V1" };
const OWN:Record<number,number[]>={3:[1,8],4:[3,6],5:[9,12],6:[2,7],7:[10,11]};
const EXALT:Record<number,number>={3:10,4:6,5:4,6:12,7:7};
const PLANET_BY_CODE:Record<string,number>={SURYA:1,CHANDRA:2,MANGALA:3,BUDHA:4,GURU:5,SHUKRA:6,SHANI:7};
function validRasi(v:number){if(!Number.isInteger(v)||v<1||v>12)throw new Error("rasi_id must be an integer from 1 to 12")}
function validBhava(v:number){if(!Number.isInteger(v)||v<1||v>12)throw new Error("bhava must be an integer from 1 to 12")}
export function isKendra(bhava:number){validBhava(bhava);return [1,4,7,10].includes(bhava)}
export function isDusthana(bhava:number){validBhava(bhava);return [6,8,12].includes(bhava)}
export function planetSignCondition(grahaId:number,rasiId:number):"OWN"|"EXALTATION"|null{validRasi(rasiId);if((OWN[grahaId]??[]).includes(rasiId))return"OWN";return EXALT[grahaId]===rasiId?"EXALTATION":null}
function find(ps:YogaPosition[],id:number){return ps.find(p=>p.graha_id===id)}
function result(rule:YogaRule,formed:boolean,matched:string[],failed:string[],evidence:Record<string,unknown>):YogaEvaluation{return{rule_code:rule.rule_code,formation_status:formed?"FORMED":"NOT_FORMED",qualification:formed?"ALL_FORMATION_CONDITIONS_MET":"FORMATION_CONDITIONS_NOT_MET",strength:formed?"PRIMARY":"NONE",matched_conditions:matched,failed_conditions:failed,evidence,engine_version:"YOGA_ENGINE_V1"}}
function evaluateMahapurusha(rule:YogaRule,ps:YogaPosition[]){const code=String(rule.formation_conditions.planet??"");const id=PLANET_BY_CODE[code];const p=id?find(ps,id):undefined;const m:string[]=[],f:string[]=[];if(!p)f.push("planet_position");else{if(isKendra(p.bhava))m.push("kendra");else f.push("kendra");const d=planetSignCondition(id,p.rasi_id);if(d)m.push(d);else f.push("own_or_exaltation_sign")}return result(rule,!f.length,m,f,{graha_id:id??null,position:p??null})}
export function evaluateYogaRule(rule:YogaRule,ps:YogaPosition[],lagnaRasiId:number){validRasi(lagnaRasiId);if(!rule?.rule_code)throw new Error("Yoga rule_code is required");const code=rule.rule_code;if(["RUCHAKA","BHADRA","HAMSA","MALAVYA","SASA"].includes(code))return evaluateMahapurusha(rule,ps);const m:string[]=[],f:string[]=[];const moon=find(ps,2),jupiter=find(ps,5);if(code==="GAJA_KESARI"){if(!moon||!jupiter)f.push("moon_and_jupiter_position");else{const d=((jupiter.bhava-moon.bhava+12)%12)+1;if([1,4,7,10].includes(d))m.push("jupiter_from_moon_kendra");else f.push("jupiter_from_moon_kendra")}}else if(code==="KEMADRUMA"){if(!moon)f.push("moon_position");else{const adjacent=ps.filter(p=>p.graha_id!==2&&(p.bhava===moon.bhava%12+1||p.bhava===(moon.bhava+10)%12+1));if(!adjacent.length)m.push("moon_adjacent_houses_empty");else f.push("moon_adjacent_houses_empty")}}else if(["VIPARITA_HARSA","VIPARITA_SARALA","VIPARITA_VIMALA"].includes(code)){const house=Number((rule.formation_conditions.lord_of as number[]|undefined)?.[0]);const lordGraha=({6:4,8:3,12:5}as Record<number,number>)[house];const p=find(ps,lordGraha);if(p&&isDusthana(p.bhava))m.push("dusthana_lord_in_dusthana");else f.push("dusthana_lord_in_dusthana")}else f.push("unsupported_rule");return result(rule,!f.length,m,f,{lagna_rasi_id:lagnaRasiId,moon:moon??null,jupiter:jupiter??null})}
export function evaluateAllYogaRules(rules:YogaRule[],ps:YogaPosition[],lagnaRasiId:number){return rules.map(r=>evaluateYogaRule(r,ps,lagnaRasiId))}
