/// <reference lib="deno.ns" />
import { evaluateAllYogaRules, evaluateYogaRule, isKendra, isDusthana, planetSignCondition } from "../../supabase/functions/jyotisha-calculator/core/yoga.ts";
const pos = [{graha_id:1,rasi_id:12,bhava:9},{graha_id:2,rasi_id:9,bhava:6},{graha_id:3,rasi_id:3,bhava:12},{graha_id:4,rasi_id:1,bhava:10},{graha_id:5,rasi_id:4,bhava:1},{graha_id:6,rasi_id:1,bhava:10},{graha_id:7,rasi_id:10,bhava:7},{graha_id:8,rasi_id:10,bhava:7},{graha_id:9,rasi_id:4,bhava:1}];
Deno.test("Yoga V1 helpers",()=>{if(!isKendra(10)||isKendra(2)||!isDusthana(8)||isDusthana(5))throw Error("house classification failed");if(planetSignCondition(5,4)!=="EXALTATION"||planetSignCondition(3,1)!=="OWN"||planetSignCondition(4,1)!==null)throw Error("dignity mapping failed")});
Deno.test("Golden Chart Mahapurusha evaluations are deterministic",()=>{const rules=[{rule_code:"HAMSA",name:"Hamsa",formation_conditions:{planet:"GURU"},planets_involved:["GURU"],houses_involved:[1,4,7,10]},{rule_code:"SASA",name:"Sasa",formation_conditions:{planet:"SHANI"},planets_involved:["SHANI"],houses_involved:[1,4,7,10]}];const out=evaluateAllYogaRules(rules,pos,4);if(out[0].formation_status!=="FORMED")throw Error("Hamsa should form");if(out[1].formation_status!=="FORMED")throw Error("Sasa should form")});
Deno.test("Mahapurusha and positional edge cases",()=>{const missing={rule_code:"HAMSA",name:"",formation_conditions:{planet:"UNKNOWN"},planets_involved:[],houses_involved:[]};if(evaluateYogaRule(missing,[],4).formation_status!=="NOT_FORMED")throw Error("missing planet fixture mismatch");const weak={rule_code:"HAMSA",name:"",formation_conditions:{planet:"GURU"},planets_involved:["GURU"],houses_involved:[1,4,7,10]};const weakPos=[{graha_id:5,rasi_id:5,bhava:2}];if(evaluateYogaRule(weak,weakPos,4).matched_conditions.length!==0)throw Error("weak Mahapurusha should not match")});
Deno.test("Gaja Kesari and Kemadruma use explicit positional conditions",()=>{const g={rule_code:"GAJA_KESARI",name:"",formation_conditions:{jupiter_from_moon:[1,4,7,10]},planets_involved:["GURU","CHANDRA"],houses_involved:[]};if(evaluateYogaRule(g,pos,4).formation_status!=="NOT_FORMED")throw Error("Gaja Kesari fixture mismatch");if(evaluateYogaRule(g,[],4).formation_status!=="NOT_FORMED")throw Error("missing Gaja Kesari positions mismatch");const formedG=evaluateYogaRule(g,[{graha_id:2,rasi_id:1,bhava:1},{graha_id:5,rasi_id:4,bhava:4}],4);if(formedG.formation_status!=="FORMED")throw Error("Gaja Kesari should form");const k={rule_code:"KEMADRUMA",name:"",formation_conditions:{adjacent_offsets:[2,12]},planets_involved:["CHANDRA"],houses_involved:[]};if(evaluateYogaRule(k,pos,4).formation_status!=="NOT_FORMED")throw Error("Kemadruma fixture mismatch");if(evaluateYogaRule(k,[],4).formation_status!=="NOT_FORMED")throw Error("missing Moon mismatch");const formedK=evaluateYogaRule(k,[{graha_id:2,rasi_id:1,bhava:1}],4);if(formedK.formation_status!=="FORMED")throw Error("Kemadruma should form")});
Deno.test("Viparita rules resolve classical house lords",()=>{for(const [code,h,expectedLord] of [["VIPARITA_HARSA",6,5],["VIPARITA_SARALA",8,7],["VIPARITA_VIMALA",12,4]] as const){const r={rule_code:code,name:"",formation_conditions:{lord_of:[h],placed_in:[6,8,12]},planets_involved:[],houses_involved:[6,8,12]};const e=evaluateYogaRule(r,pos,4);if((e.evidence as any).lord_house!==h||(e.evidence as any).lord_graha_id!==expectedLord)throw Error("Viparita lord resolution mismatch")}const formed=evaluateYogaRule({rule_code:"VIPARITA_HARSA",name:"",formation_conditions:{lord_of:[6],placed_in:[6,8,12]},planets_involved:[],houses_involved:[6,8,12]},[{graha_id:5,rasi_id:9,bhava:6}],4);if(formed.formation_status!=="FORMED")throw Error("Viparita should form")});
Deno.test("unsupported Yoga rule remains deterministic",()=>{const e=evaluateYogaRule({rule_code:"X",name:"",formation_conditions:{},planets_involved:[],houses_involved:[]},pos,4);if(e.formation_status!=="NOT_FORMED"||e.failed_conditions[0]!=="unsupported_rule"||e.evidence.lord_house!==null||e.evidence.lord_graha_id!==null)throw Error("unsupported Yoga evidence mismatch")});
Deno.test("rejects invalid inputs",()=>{for(const f of [()=>isKendra(13),()=>isDusthana(0),()=>planetSignCondition(5,13),()=>evaluateYogaRule({rule_code:"X",name:"",formation_conditions:{},planets_involved:[],houses_involved:[]},pos,13),()=>evaluateYogaRule({rule_code:"VIPARITA_HARSA",name:"",formation_conditions:{lord_of:[13]},planets_involved:[],houses_involved:[]},pos,4),()=>evaluateYogaRule({rule_code:"",name:"",formation_conditions:{},planets_involved:[],houses_involved:[]},pos,4)]){let failed=false;try{f()}catch{failed=true}if(!failed)throw Error("invalid input accepted")}});
